Updated promote.yml

diff --git a/azure-pipelines/promote.yml b/azure-pipelines/promote.yml
--- a/azure-pipelines/promote.yml
+++ b/azure-pipelines/promote.yml
@@ -31,21 +31,233 @@ stages:
 - stage: promote
   displayName: 'promote version'
   jobs:
-  - job: Promot
-    displayName: 'promot version'
+  - job: Promote_Front
+    displayName: "Promot Front: ${{ parameters.TARGET_CHANNEL }}"
     steps:
+    - checkout: none
     - script: |
         if [ "$(Build.SourceBranch)" != "refs/heads/cicd" ]; then
           echo "❌ This pipeline is locked to cicd only"
           exit 1
         fi
-      displayName: "Enforce cicd execution"
+      displayName: "Enforcing cicd branch"
+    
+    - task: Bash@3
+      name: init
+      displayName: 'init: '
+      env:
+        VERSION_INPUT: ${{ parameters.VERSION }}
+        TARGET_CHANNEL: ${{ parameters.TARGET_CHANNEL }}
+      inputs:
+        targetType: 'inline'
+        script: |
+          SOURCE_BRANCH=$(echo "$TARGET_CHANNEL" | cut -d_ -f1)
+          TARGET_BRANCH=$(echo "$TARGET_CHANNEL" | cut -d_ -f3)
+          
+          echo "SOURCE_BRANCH: $SOURCE_BRANCH"
+          echo "TARGET_BRANCH: $TARGET_BRANCH"
+          echo "VERSION_INPUT: $VERSION_INPUT"
+          
+          if [ $VERSION_INPUT == "0.0.0"  ]; then
+              echo "❌ Version is required !"
+              exit 1
+          fi
+    
+          echo "##vso[task.setvariable variable=SOURCE_BRANCH;isOutput=true]$SOURCE_BRANCH"
+          echo "##vso[task.setvariable variable=TARGET_BRANCH;isOutput=true]$TARGET_BRANCH"
+          echo "##vso[task.setvariable variable=VERSION_INPUT;isOutput=true]$VERSION_INPUT"
+    
+    
+    - bash: |
+        set -e
+        echo "username:S_Bot_Azure" >> ~/.git-credentials
+        echo "password:$(System.AccessToken)" >> ~/.git-credentials
+    
+        # Configure Git
+        git config --global credential.helper store
+        git config --global credential.useHttpPath true
+        git config --global user.email "S_Bot_Azure@sadgan.int"
+        git config --global user.name "S_Bot_Azure"
+        git config --global http.sslVerify false
+        git config --global --add safe.directory '*'
+        git config --global core.compression 0
+        git config --global http.postBuffer 1048576000
+        git config --global pack.threads 1
+        git config --global pull.rebase false
+        
+        
+        BASE_URL="http://S_Bot_Azure:$(System.AccessToken)@azure.sadgan.int/WebApp"
+        
+        function clone_or_pull {
+    
+            git config --global http.sslVerify false
+            git config --global --add safe.directory '*'
+    
+            branch_name=$1
+            repo_url=$2
+            target_dir=$3
+        
+            echo "$repo_url" > ~/.git-credentials
+    
+            echo "Cleaning up previous checkout ($target_dir)..."
+            if [ -d "$target_dir" ]; then
+                echo "Removing directory..."
+                rm -rf "$target_dir"
+            fi
+        
+      
+            echo "Cloning $target_dir from branch $branch_name..."
+            
+      
+            # Clone using environment variable for credentials
+            echo "Cloning $repo_url (branch: $branch_name) into $target_dir..."
+            # git clone --branch "$branch_name" "$repo_url" "$target_dir"
+            # git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" clone --single-branch --branch "$branch_name"     "$repo_url"    "$target_dir"
+    
+            git clone --single-branch --branch "$branch_name" "$repo_url"   "$target_dir"
+                
+                  
+            if [ $? -eq 0 ] && [ -d "$target_dir/.git" ]; then
+                cd "$target_dir"
+                echo "Current directory: $pwd"
+                echo "✅ Repository cloned to: $target_dir"
+                echo "📁 Directory contents:"
+                ls -la
+            else
+                echo "❌ Clone failed"
+                exit 1
+            fi
+        }     
+    
+    
+    
+        clone_or_pull  cicd                      "$BASE_URL/SadganErp/_git/CICD"                 "$(System.DefaultWorkingDirectory)/CICD"    
+        clone_or_pull  $(init.TARGET_BRANCH)     "$BASE_URL/SadganErp/_git/Sadgan.Erp.Panel"     "$(System.DefaultWorkingDirectory)/SadganErp/Sadgan.Erp.Panel/$(init.TARGET_BRANCH)" 
+        clone_or_pull  $(init.SOURCE_BRANCH)     "$BASE_URL/SadganErp/_git/Sadgan.Erp.Panel"     "$(System.DefaultWorkingDirectory)/SadganErp/Sadgan.Erp.Panel/$(init.SOURCE_BRANCH)"
+                      
+        
+        echo "Final directory structure:"
+        ls -R | head -15
+      displayName: 'Git Checkout'
+      env:
+        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+
     - template: azure-pipelines/templates/promote-version.yml@templates
       parameters:
         TARGET_CHANNEL: "${{ parameters.TARGET_CHANNEL }}"
         VERSION: "${{  parameters.VERSION  }}"
         ProjPath: "SadganErp/Sadgan.Erp.Panel"
-        Collection: "SadganErp"
-        Repo: "SadganErp/_git/Sadgan.Erp.Panel"
-        BranchName: "cicd"
         side: "frontend"
+
+  - job: Promote_Backend
+    dependsOn: Promote_Front
+    condition: succeeded()
+    displayName: "Promote Back: ${{ parameters.TARGET_CHANNEL }}"
+    steps:
+    - checkout: none
+    - task: Bash@3
+      name: init
+      displayName: 'init: '
+      env:
+        VERSION_INPUT: ${{ parameters.VERSION }}
+        TARGET_CHANNEL: ${{ parameters.TARGET_CHANNEL }}
+      inputs:
+        targetType: 'inline'
+        script: |
+          SOURCE_BRANCH=$(echo "$TARGET_CHANNEL" | cut -d_ -f1)
+          TARGET_BRANCH=$(echo "$TARGET_CHANNEL" | cut -d_ -f3)
+          
+          echo "SOURCE_BRANCH: $SOURCE_BRANCH"
+          echo "TARGET_BRANCH: $TARGET_BRANCH"
+          echo "VERSION_INPUT: $VERSION_INPUT"
+          
+          if [ $VERSION_INPUT == "0.0.0"  ]; then
+              echo "❌ Version is required !"
+              exit 1
+          fi
+    
+          echo "##vso[task.setvariable variable=SOURCE_BRANCH;isOutput=true]$SOURCE_BRANCH"
+          echo "##vso[task.setvariable variable=TARGET_BRANCH;isOutput=true]$TARGET_BRANCH"
+          echo "##vso[task.setvariable variable=VERSION_INPUT;isOutput=true]$VERSION_INPUT"
+    
+    
+    - bash: |
+        set -e
+        echo "username:S_Bot_Azure" >> ~/.git-credentials
+        echo "password:$(System.AccessToken)" >> ~/.git-credentials
+    
+        # Configure Git
+        git config --global credential.helper store
+        git config --global credential.useHttpPath true
+        git config --global user.email "S_Bot_Azure@sadgan.int"
+        git config --global user.name "S_Bot_Azure"
+        git config --global http.sslVerify false
+        git config --global --add safe.directory '*'
+        git config --global core.compression 0
+        git config --global http.postBuffer 1048576000
+        git config --global pack.threads 1
+        git config --global pull.rebase false
+        
+        
+        BASE_URL="http://S_Bot_Azure:$(System.AccessToken)@azure.sadgan.int/WebApp"
+        
+        function clone_or_pull {
+    
+            git config --global http.sslVerify false
+            git config --global --add safe.directory '*'
+    
+            branch_name=$1
+            repo_url=$2
+            target_dir=$3
+        
+            echo "$repo_url" > ~/.git-credentials
+    
+            echo "Cleaning up previous checkout ($target_dir)..."
+            if [ -d "$target_dir" ]; then
+                echo "Removing directory..."
+                rm -rf "$target_dir"
+            fi
+        
+      
+            echo "Cloning $target_dir from branch $branch_name..."
+            
+      
+            # Clone using environment variable for credentials
+            echo "Cloning $repo_url (branch: $branch_name) into $target_dir..."
+            # git clone --branch "$branch_name" "$repo_url" "$target_dir"
+            # git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" clone --single-branch --branch "$branch_name"     "$repo_url"    "$target_dir"
+    
+            git clone --single-branch --branch "$branch_name" "$repo_url"   "$target_dir"
+                
+                  
+            if [ $? -eq 0 ] && [ -d "$target_dir/.git" ]; then
+                cd "$target_dir"
+                echo "Current directory: $pwd"
+                echo "✅ Repository cloned to: $target_dir"
+                echo "📁 Directory contents:"
+                ls -la
+            else
+                echo "❌ Clone failed"
+                exit 1
+            fi
+        }     
+    
+    
+    
+        clone_or_pull  cicd                      "$BASE_URL/SadganErp/_git/CICD"             "$(System.DefaultWorkingDirectory)/CICD"    
+        clone_or_pull  $(init.TARGET_BRANCH)     "$BASE_URL/SadganErp/_git/SadganErpApi"     "$(System.DefaultWorkingDirectory)/SadganErp/SadganErpApi/$(init.TARGET_BRANCH)" 
+        clone_or_pull  $(init.SOURCE_BRANCH)     "$BASE_URL/SadganErp/_git/SadganErpApi"     "$(System.DefaultWorkingDirectory)/SadganErp/SadganErpApi/$(init.SOURCE_BRANCH)"
+                      
+        
+        echo "Final directory structure:"
+        ls -R | head -15
+      displayName: 'Git Checkout'
+      env:
+        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+
+    - template: azure-pipelines/templates/promote-version.yml@templates
+      parameters:
+        TARGET_CHANNEL: "${{ parameters.TARGET_CHANNEL }}"
+        VERSION: "${{  parameters.VERSION  }}"
+        ProjPath: "SadganErp/SadganErpApi"
+        side: "backend"        
